routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\TransactionController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/categories', CategoryController::class);
Route::resource('/items', ItemController::class);
Route::resource('/transactions', TransactionController::class);

resources/views/modals/category-create.blade.php
<!-- Modal -->
<div class="modal fade" id="category-create" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">New Category</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('categories.store')}}" method="POST" autocomplete="off">
            @csrf
            @method('POST')
                <div class="modal-body">   
                    <div class="form-group">
                        <label for="name">Category Name</label>
                        <input type="text" name="name" placeholder="Category Name" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/modals/category-delete.blade.php
<!-- Modal -->
<div class="modal fade" id="category-delete-{{$category->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-danger text-white">
                <h5 class="modal-title" id="exampleModalLongTitle">Delete Category</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>            
            <div class="modal-body">   
                Are you sure you wish to delete <b class="text-danger">{{$category->name}}</b> category?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Close</button>
                <form action="{{route('categories.destroy', $category)}}" method="POST" autocomplete="off">
                    @csrf
                    @method('DELETE')
                <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>           
        </div>
    </div>
</div>

resources/views/modals/category-edit.blade.php
<!-- Modal -->
<div class="modal fade" id="category-edit-{{$category->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Edit Category</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('categories.update', $category)}}" method="POST" autocomplete="off">
            @csrf
            @method('PUT')
                <div class="modal-body">   
                    <div class="form-group">
                        <label for="name">Category Name</label>
                        <input type="text" name="name" value="{{$category->name}}" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/modals/item-create-log.blade.php
<!-- Modal -->
<div class="modal fade" id="item-create-log" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">New Transaction Log Entry</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('transactions.store')}}" method="POST" autocomplete="off">
            @csrf
            @method('POST')
            {{-- <form action="" method="GET" autocomplete="off"> --}}
                <div class="modal-body">
                    <div class="form-group">
                        <label for="name">Title</label>
                        <input type="text" name="title" placeholder="Log Title" class="form-control">
                    </div>                    
                    <div class="form-group">
                        <label for="name">Comment (Optional)</label>
                        <textarea type="text" name="comment" placeholder="Comment" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="count">Quantity</label>
                        <input type="number" name="count" placeholder="Quantity" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="type">Type of Transaction</label>
                        <select name="type" class="custom-select">
                            <option value="in">Purchase</option>
                            <option value="out">Sale</option>   
                            <option value="out">Discard</option>  
                            <option value="out">Damaged</option>                               
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="number" name="item_id" value="{{$item->id}}" class="form-control" hidden>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/modals/item-create.blade.php
<!-- Modal -->
<div class="modal fade" id="item-create" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">New Item</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('items.store')}}" method="POST" autocomplete="off">
            @csrf
            @method('POST')
            {{-- <form action="" method="GET" autocomplete="off"> --}}
                <div class="modal-body">   
                    <div class="form-group">
                        <label for="name">Item Name</label>
                        <input type="text" name="name" placeholder="Item Name" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="name">Description</label>
                        <textarea type="text" name="description" placeholder="Description" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="name">Category</label>
                        <select name="category_id" class="custom-select">
                            <option value="">-- Select Category --</option>
                            @foreach ($categories as $category)
                                <option value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach                            
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/modals/item-delete.blade.php
<!-- Modal -->
<div class="modal fade" id="item-delete-{{$item->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-danger text-white">
                <h5 class="modal-title" id="exampleModalLongTitle">Delete Item</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>            
            <div class="modal-body">   
                Are you sure you wish to delete <span class="text-danger"><b>{{$item->name}}</b> - {{$item->description}}</span>?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Close</button>
                <form action="{{route('items.destroy', $item)}}" method="POST" autocomplete="off">
                    @csrf
                    @method('DELETE')
                <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>           
        </div>
    </div>
</div>

resources/views/modals/item-edit.blade.php
<!-- Modal -->
<div class="modal fade" id="item-edit-{{$item->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Edit Item</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('items.update', $item)}}" method="POST" autocomplete="off">
            @csrf
            @method('PUT')
                <div class="modal-body">   
                    <div class="form-group">
                        <label for="name">Item Name</label>
                        <input type="text" name="name" value="{{$item->name}}" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="name">Description</label>
                        <textarea type="text" name="description" class="form-control">{{$item->description}}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="name">Category</label>
                        <select name="category_id" class="custom-select">
                                <option value="{{$item->category->id}}" selected>{{$item->category->name}}</option>
                            @foreach ($categories as $category)
                                @if ($category->id !== $item->category->id)
                                <option value="{{$category->id}}">{{$category->name}}</option>
                                @endif                                
                            @endforeach                            
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>